# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mathpresso-test' do
  use_frameworks!

  # Pods for Mathpresso-test
  pod 'Alamofire', '4.8.2'
  pod 'SDWebImage', '~> 5.0'
end
